// Generated by gencpp from file naloga1/CustomMessage.msg
// DO NOT EDIT!


#ifndef NALOGA1_MESSAGE_CUSTOMMESSAGE_H
#define NALOGA1_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naloga1
{
template <class ContainerAllocator>
struct CustomMessage_
{
  typedef CustomMessage_<ContainerAllocator> Type;

  CustomMessage_()
    : content()
    , messageid(0)  {
    }
  CustomMessage_(const ContainerAllocator& _alloc)
    : content(_alloc)
    , messageid(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _content_type;
  _content_type content;

   typedef int32_t _messageid_type;
  _messageid_type messageid;





  typedef boost::shared_ptr< ::naloga1::CustomMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naloga1::CustomMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessage_

typedef ::naloga1::CustomMessage_<std::allocator<void> > CustomMessage;

typedef boost::shared_ptr< ::naloga1::CustomMessage > CustomMessagePtr;
typedef boost::shared_ptr< ::naloga1::CustomMessage const> CustomMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naloga1::CustomMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naloga1::CustomMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naloga1::CustomMessage_<ContainerAllocator1> & lhs, const ::naloga1::CustomMessage_<ContainerAllocator2> & rhs)
{
  return lhs.content == rhs.content &&
    lhs.messageid == rhs.messageid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naloga1::CustomMessage_<ContainerAllocator1> & lhs, const ::naloga1::CustomMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naloga1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::naloga1::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naloga1::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naloga1::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naloga1::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naloga1::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naloga1::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naloga1::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "864b609b211ae0d55c32c0f3fdb0a59b";
  }

  static const char* value(const ::naloga1::CustomMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x864b609b211ae0d5ULL;
  static const uint64_t static_value2 = 0x5c32c0f3fdb0a59bULL;
};

template<class ContainerAllocator>
struct DataType< ::naloga1::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naloga1/CustomMessage";
  }

  static const char* value(const ::naloga1::CustomMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naloga1::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string content\n"
"int32 messageid\n"
;
  }

  static const char* value(const ::naloga1::CustomMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naloga1::CustomMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
      stream.next(m.messageid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naloga1::CustomMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naloga1::CustomMessage_<ContainerAllocator>& v)
  {
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.content);
    s << indent << "messageid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.messageid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NALOGA1_MESSAGE_CUSTOMMESSAGE_H
