// Generated by gencpp from file naloga1/Message1.msg
// DO NOT EDIT!


#ifndef NALOGA1_MESSAGE_MESSAGE1_H
#define NALOGA1_MESSAGE_MESSAGE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naloga1
{
template <class ContainerAllocator>
struct Message1_
{
  typedef Message1_<ContainerAllocator> Type;

  Message1_()
    : content()  {
    }
  Message1_(const ContainerAllocator& _alloc)
    : content(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _content_type;
  _content_type content;





  typedef boost::shared_ptr< ::naloga1::Message1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naloga1::Message1_<ContainerAllocator> const> ConstPtr;

}; // struct Message1_

typedef ::naloga1::Message1_<std::allocator<void> > Message1;

typedef boost::shared_ptr< ::naloga1::Message1 > Message1Ptr;
typedef boost::shared_ptr< ::naloga1::Message1 const> Message1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naloga1::Message1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naloga1::Message1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naloga1::Message1_<ContainerAllocator1> & lhs, const ::naloga1::Message1_<ContainerAllocator2> & rhs)
{
  return lhs.content == rhs.content;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naloga1::Message1_<ContainerAllocator1> & lhs, const ::naloga1::Message1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naloga1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::naloga1::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naloga1::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naloga1::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naloga1::Message1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naloga1::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naloga1::Message1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naloga1::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e84951ee6d0addf437bfddd5b19734";
  }

  static const char* value(const ::naloga1::Message1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e84951ee6d0addULL;
  static const uint64_t static_value2 = 0xf437bfddd5b19734ULL;
};

template<class ContainerAllocator>
struct DataType< ::naloga1::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naloga1/Message1";
  }

  static const char* value(const ::naloga1::Message1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naloga1::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string content\n"
;
  }

  static const char* value(const ::naloga1::Message1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naloga1::Message1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naloga1::Message1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naloga1::Message1_<ContainerAllocator>& v)
  {
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.content);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NALOGA1_MESSAGE_MESSAGE1_H
