// Generated by gencpp from file naloga1/SumRequest.msg
// DO NOT EDIT!


#ifndef NALOGA1_MESSAGE_SUMREQUEST_H
#define NALOGA1_MESSAGE_SUMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naloga1
{
template <class ContainerAllocator>
struct SumRequest_
{
  typedef SumRequest_<ContainerAllocator> Type;

  SumRequest_()
    : nums()  {
    }
  SumRequest_(const ContainerAllocator& _alloc)
    : nums(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _nums_type;
  _nums_type nums;





  typedef boost::shared_ptr< ::naloga1::SumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naloga1::SumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SumRequest_

typedef ::naloga1::SumRequest_<std::allocator<void> > SumRequest;

typedef boost::shared_ptr< ::naloga1::SumRequest > SumRequestPtr;
typedef boost::shared_ptr< ::naloga1::SumRequest const> SumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naloga1::SumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naloga1::SumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::naloga1::SumRequest_<ContainerAllocator1> & lhs, const ::naloga1::SumRequest_<ContainerAllocator2> & rhs)
{
  return lhs.nums == rhs.nums;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::naloga1::SumRequest_<ContainerAllocator1> & lhs, const ::naloga1::SumRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace naloga1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::naloga1::SumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naloga1::SumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naloga1::SumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naloga1::SumRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naloga1::SumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naloga1::SumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naloga1::SumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28f7951279f923f12b6868d35afe7af6";
  }

  static const char* value(const ::naloga1::SumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28f7951279f923f1ULL;
  static const uint64_t static_value2 = 0x2b6868d35afe7af6ULL;
};

template<class ContainerAllocator>
struct DataType< ::naloga1::SumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naloga1/SumRequest";
  }

  static const char* value(const ::naloga1::SumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naloga1::SumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"int32[] nums\n"
;
  }

  static const char* value(const ::naloga1::SumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naloga1::SumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nums);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naloga1::SumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naloga1::SumRequest_<ContainerAllocator>& v)
  {
    s << indent << "nums[]" << std::endl;
    for (size_t i = 0; i < v.nums.size(); ++i)
    {
      s << indent << "  nums[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.nums[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NALOGA1_MESSAGE_SUMREQUEST_H
