// Generated by gencpp from file naloga1/Sum.msg
// DO NOT EDIT!


#ifndef NALOGA1_MESSAGE_SUM_H
#define NALOGA1_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <naloga1/SumRequest.h>
#include <naloga1/SumResponse.h>


namespace naloga1
{

struct Sum
{

typedef SumRequest Request;
typedef SumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sum
} // namespace naloga1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naloga1::Sum > {
  static const char* value()
  {
    return "703b51aee7a7c5741886072d7be5fc8e";
  }

  static const char* value(const ::naloga1::Sum&) { return value(); }
};

template<>
struct DataType< ::naloga1::Sum > {
  static const char* value()
  {
    return "naloga1/Sum";
  }

  static const char* value(const ::naloga1::Sum&) { return value(); }
};


// service_traits::MD5Sum< ::naloga1::SumRequest> should match
// service_traits::MD5Sum< ::naloga1::Sum >
template<>
struct MD5Sum< ::naloga1::SumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naloga1::Sum >::value();
  }
  static const char* value(const ::naloga1::SumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naloga1::SumRequest> should match
// service_traits::DataType< ::naloga1::Sum >
template<>
struct DataType< ::naloga1::SumRequest>
{
  static const char* value()
  {
    return DataType< ::naloga1::Sum >::value();
  }
  static const char* value(const ::naloga1::SumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naloga1::SumResponse> should match
// service_traits::MD5Sum< ::naloga1::Sum >
template<>
struct MD5Sum< ::naloga1::SumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naloga1::Sum >::value();
  }
  static const char* value(const ::naloga1::SumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naloga1::SumResponse> should match
// service_traits::DataType< ::naloga1::Sum >
template<>
struct DataType< ::naloga1::SumResponse>
{
  static const char* value()
  {
    return DataType< ::naloga1::Sum >::value();
  }
  static const char* value(const ::naloga1::SumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NALOGA1_MESSAGE_SUM_H
